-------------------------------------------------------------------------------
Test set: tech.rongxing.devops.whitebox.Example1Test
-------------------------------------------------------------------------------
Tests run: 20, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.039 s <<< FAILURE! - in tech.rongxing.devops.whitebox.Example1Test
testWithCsvSource{int, int, int, int}[2]  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <3> but was: <2>
	at tech.rongxing.devops.whitebox.Example1Test.testWithCsvSource(Example1Test.java:77)

testWithCsvSource{int, int, int, int}[3]  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <4> but was: <2>
	at tech.rongxing.devops.whitebox.Example1Test.testWithCsvSource(Example1Test.java:77)

testWithCsvSourceFile{String, int, int, int, int, String}[2]  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 2分支覆盖没有通过 ==> expected: <3> but was: <2>
	at tech.rongxing.devops.whitebox.Example1Test.testWithCsvSourceFile(Example1Test.java:93)

testWithCsvSourceFile{String, int, int, int, int, String}[3]  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 3条件覆盖没有通过 ==> expected: <4> but was: <2>
	at tech.rongxing.devops.whitebox.Example1Test.testWithCsvSourceFile(Example1Test.java:93)

testFunc1{String, boolean, String}[2]  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 普通判断 ==> expected: <true> but was: <false>
	at tech.rongxing.devops.whitebox.Example1Test.testFunc1(Example1Test.java:63)

testFunc2_2{String, boolean, String}[2]  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 普通判断 ==> expected: <true> but was: <false>
	at tech.rongxing.devops.whitebox.Example1Test.testFunc2_2(Example1Test.java:85)

